#!/bin/bash

CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
MEM=$(free | awk '/Mem:/ {printf("%.2f"), $3/$2 * 100}')
DISK=$(df / | awk 'NR==2 {print $5}' | sed 's/%//')

echo "CPU: $CPU%"
echo "Memory: $MEM%"
echo "Disk: $DISK%"

# Alerts
if (( ${CPU%.*} > 80 )); then
  echo "ALERT: CPU usage is above 80%" 
fi

if (( ${MEM%.*} > 80 )); then
  echo "ALERT: Memory usage is above 80%" 
fi

if (( $DISK > 80 )); then
  echo "ALERT: Disk usage is above 80%" 
fi
